added blog section
PrimewiseConsulting/Primewise-website pull request #1
Opened 2023-09-20 17:08 UTC by GauravTheBeginner

2023-10-01 10:36 UTC, PrimewiseConsulting requested changes

2023-10-01 10:36 UTC, PrimewiseConsulting commented on app/blogs/[title]/page.tsx
> +
remove extra line here

2023-10-01 10:36 UTC, PrimewiseConsulting commented on app/blogs/[title]/page.tsx
> +
extra line should be removed from here

2023-10-01 10:36 UTC, PrimewiseConsulting commented on app/blogs/page.tsx
> +      export default bloglist;
remove extra space before export. The code should be properly indented

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +
remove extra line

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +
remove extra line

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +
remove extra line

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +              {tags.map((tag, index) => (
what is tag element?

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +                <p className="text-gray-700 dark:text-gray-300 text-lg mb-2">{post.point1}</p>
instead of point , lets rename it as post.subheading1, post.subheading2 ....etc

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +                <p className="text-gray-700 dark:text-gray-300 text-lg mb-8">{post.point3para}</p>
rename it as post.para3 and similarly for others

2023-10-01 10:36 UTC, PrimewiseConsulting commented on components/Blog/blogData.tsx
> +    rltitle: "Real-Life Success Stories:",
what is rl here?

2023-10-01 10:36 UTC, PrimewiseConsulting commented on types/post.ts
> +    rltitle:string;
what is rl here?

2023-10-01 10:39 UTC, GauravTheBeginner commented on components/Blog/blogData.tsx
> +    rltitle: "Real-Life Success Stories:",
real life title

2023-10-01 11:22 UTC, GauravTheBeginner commented on components/Blog/Fullpost.tsx
> +              {tags.map((tag, index) => (
Tags are those that tell whether this blog is designed, informative or creative.

2023-10-01 11:30 UTC, GauravTheBeginner commented on components/Blog/Fullpost.tsx
> +
did it

2023-10-01 11:31 UTC, GauravTheBeginner commented on components/Blog/Fullpost.tsx
> +                <p className="text-gray-700 dark:text-gray-300 text-lg mb-2">{post.point1}</p>
ok

2023-10-02 15:20 UTC, PrimewiseConsulting commented on components/Blog/Fullpost.tsx
> +              {tags.map((tag, index) => (
ok

2023-10-03 06:54 UTC, merged