added faq page
PrimewiseConsulting/Primewise-website pull request #9
Opened 2023-10-21 17:16 UTC by Dilnazzzshaikh

2023-10-21 17:18 UTC, GauravTheBeginner submitted a review, later dismissed

2023-10-24 12:54 UTC, PrimewiseConsulting requested changes

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +import FAQComponent1 from "../../components/FAQ/SeparetePageFaq";
rename the page SeparetePageFaq to faqPage

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +import FAQComponent1 from "../../components/FAQ/SeparetePageFaq";
what is FAQComponent1 ?

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +
why are here extra line spacing given?

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +        <SectionTitle title="Frequently Asked Questions" paragraph="" center />
since  paragraph=""  is empty , do we really need it?

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +        <div></div>
why do we extra empty div here?

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +
no need of extra line spacing

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/faq/page.tsx
> +
same here, this line must be deleted

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/page.tsx
> +      { <Video /> }
we dont need {} around Video component , We can remove it and make it consistent as other components.

2023-10-24 12:54 UTC, PrimewiseConsulting commented on app/page.tsx
> +      <FAQComponent/>
change  FAQComponent/ to  FAQComponent / to improve consistency

2023-10-24 12:54 UTC, PrimewiseConsulting commented on components/FAQ/FAQComponent.tsx
> +  const faqData = [
lets make a separate data file for faqData and put the data there, here we should only have the component loading code.

2023-10-24 12:54 UTC, PrimewiseConsulting commented on components/FAQ/FAQComponent.tsx
> +
why these extra lines here ?

2023-10-24 12:54 UTC, PrimewiseConsulting commented on components/FAQ/SeparetePageFaq.tsx
> +const SeparetePageFaq = () => {
rename this page.

2023-10-24 12:54 UTC, PrimewiseConsulting commented on components/FAQ/SeparetePageFaq.tsx
> +  const faqData = [
again put the data in separate page and load it from there

2023-11-03 07:58 UTC, Dilnazzzshaikh reviewed
all changes are done

2023-11-03 08:08 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +import FAQComponent1 from "../../components/FAQ/SeparetePageFaq";
renamed the page to faqPage

2023-11-03 08:10 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +        <SectionTitle title="Frequently Asked Questions" paragraph="" center />
Doesn't need of paragraph so removed it

2023-11-03 08:11 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +import FAQComponent1 from "../../components/FAQ/SeparetePageFaq";
Removed FAQComponant1

2023-11-03 08:11 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +
Extra line spaces are removed

2023-11-03 08:11 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +        <div></div>
Removed empty div tag

2023-11-03 08:12 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +
Removed extra line spacing

2023-11-03 08:12 UTC, Dilnazzzshaikh commented on app/faq/page.tsx
> +
Deleted extra line space

2023-11-03 08:13 UTC, Dilnazzzshaikh commented on app/page.tsx
> +      { <Video /> }
removed {} around Video component

2023-11-03 08:13 UTC, Dilnazzzshaikh commented on app/page.tsx
> +      <FAQComponent/>
changed FAQComponent/ to FAQComponent /

2023-11-03 08:14 UTC, Dilnazzzshaikh commented on components/FAQ/FAQComponent.tsx
> +
extra lines are removed

2023-11-03 08:15 UTC, Dilnazzzshaikh commented on components/FAQ/SeparetePageFaq.tsx
> +const SeparetePageFaq = () => {
renamed SeparetePageFaq to faqPage

2023-11-03 08:15 UTC, Dilnazzzshaikh commented on components/FAQ/SeparetePageFaq.tsx
> +  const faqData = [
created new file to store data,and accessed from there

2023-11-03 08:16 UTC, Dilnazzzshaikh reviewed
Changes are done

2023-11-03 11:03 UTC, GauravTheBeginner approved these changes

2023-11-05 17:17 UTC, PrimewiseConsulting approved these changes

2023-11-05 17:17 UTC, merged